config/routes.rb
MatchingTool::Application.routes.draw do

  root  'home#about'
  match '/about',    to: 'home#about',    via: 'get'
  match '/contact',   to: 'home#contact',   via: 'get'
  match '/scholarships',   to: 'home#scholarships',   via: 'get'

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
  end

  def contact
  end

  def scholarships
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def controller?(*controller)
    controller.include?(params[:controller])
  end

  def action?(*action)
    action.include?(params[:action])
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<div class="row about-row">
	<div class="col-md-3 about-column-header">
		<h1>About</h1>
  </div>
  <div class="col-md-7 side-header">
		<p>Looking for a scholarship? Complete our survey and meet with Millie Reidy in the library to discuss your opportunities. Take a look at a map of where some of your classmates have gone with their scholarships.</p>
  </div>
</div>
<div class="row">
  <div class="col-md-12 about-column-map">
		<iframe width='100%' 
				height='500px' 
				frameBorder='0' 
				src='https://a.tiles.mapbox.com/v3/jackreidy.gle94jmh/mm/zoompan,zoomwheel.html?secure=1#4/38.79/-97.73'>
		</iframe>
  </div>
</div>
<div class="row about-row">
  <div class="col-md-10 bottom-section">
  	<p> Ready to complete the compatability quiz? </p>
  </div>
  <div class="col-md-2 bottom-section">
  	<button type="button" class="btn btn-default btn-lg">I'm ready!</button>
  </div>
</div>

app/views/home/contact.html.erb
<h1>Home#contact</h1>
<p>Find me in app/views/home/contact.html.erb</p>

app/views/home/scholarships.html.erb
<h1>Home#scholarships</h1>
<p>Find me in app/views/home/scholarships.html.erb</p>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand">Wood River Scholars</div>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "WRHS Homepage" , "http://blaineschools.org/Schools/WRHS/" %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<li 
	<% if controller?("home") && action?("about") %>
		<%= "class=active" %>
	<% end %> 
	><%= link_to "About" , about_path %></li>

<li
	<% if controller?("home") && action?("contact") %>
		<%= "class=active" %>
	<% end %> 
	><%= link_to "Contact" , contact_path %></li>

<li
	<% if controller?("home") && action?("scholarships") %>
		<%= "class=active" %>
	<% end %> 
	><%= link_to "Scholarships" , scholarships_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Matching Tool" %></title>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Matching Tool" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main" class="main_background">
      <div class="container content-container">
        <%= render 'layouts/messages' %>
        <%= yield %>
      </div>
    </main>
  </body>
</html>